version: '3.7'

services:
  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgres
    env_file: .env
    image: dpage/pgadmin4
    networks:
      - postgres-network
    ports:
      - '5050:80'
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin:rw

  postgres:
    container_name: postgres
    env_file: .env
    image: postgres:alpine
    networks:
      - postgres-network
    ports:
      - '5433:5432'
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - redis-network
    ports:
      - '6380:6379'
    restart: unless-stopped
    volumes:
      - redis-data:/var/lib/redis:rw

  wikijs:
    container_name: wikijs
    depends_on:
      - postgres
    env_file: .env
    environment:
      DB_HOST: postgres
      DB_NAME: wiki
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
      DB_TYPE: postgres
      DB_USER: ${POSTGRES_USER}
    image: requarks/wiki:latest
    networks:
      - postgres-network
    ports:
      - '3000:3000'
    restart: unless-stopped

volumes:
  pgadmin-data: {}
  pgdata: {}
  redis-data: {}

networks:
  postgres-network: {}
  redis-network: {}
